sources:
  - name: GNews-cn
    language: zh
    country: cn
    timeout: 30
    enabled: true
    type: gnews
  - name: GNews-us
    language: en
    country: us
    timeout: 30
    enabled: true
    type: gnews
  - name: GNews-fr
    language: fr
    country: fr
    timeout: 30
    enabled: true
    type: gnews
  - name: GNews-gb
    language: en
    country: gb
    timeout: 30
    enabled: true
    type: gnews
  - name: GNews-hk
    language: zh
    country: hk
    timeout: 30
    enabled: true
    type: gnews
  - name: GNews-ru
    language: ru
    country: ru
    timeout: 30
    enabled: true
    type: gnews
  - name: GNews-ua
    language: uk
    country: ua
    timeout: 30
    enabled: true
    type: gnews
  - name: GNews-tw
    language: zh
    country: tw
    timeout: 30
    enabled: true
    type: gnews
  - name: GNews-sg
    language: en
    country: sg
    timeout: 30
    enabled: true
    type: gnews
  - name: GNews-jp
    language: ja
    country: jp
    timeout: 30
    enabled: true
    type: gnews
  - name: GNews-br
    language: pt
    country: br
    timeout: 30
    enabled: true
    type: gnews
  - name: GNews-ar
    language: es
    country: ar
    timeout: 30
    enabled: true
    type: gnews
  - name: Blockbeats
    type: blockbeats
    enabled: true
    timeout: 30

